Repository neoforged/FancyModLoader, pull requests merged in 2023-12, with the labels that each got.

#43 Expect either NSF in `loadResourceFromModFile`
  loader/src/main/java/net/neoforged/fml/loading/moddiscovery/AbstractJarFileDependencyLocator.java
Labels: bug

#48 Allow loading configs from a specified override path
  core/src/main/java/net/neoforged/fml/config/ConfigFileTypeHandler.java
  core/src/main/java/net/neoforged/fml/config/ConfigTracker.java
Labels: enhancement, breaking-change

#21 Add implementations of IModFileInfo#showAsDataPack for data pack grouping
  gradle.properties
  loader/src/main/java/net/neoforged/fml/loading/moddiscovery/AbstractModProvider.java
  loader/src/main/java/net/neoforged/fml/loading/moddiscovery/ModFileInfo.java
Labels: enhancement, breaking-change

#53 Get rid of CTS and OHD
  loader/src/main/java/net/neoforged/fml/common/asm/CapabilityTokenSubclass.java
  loader/src/main/java/net/neoforged/fml/common/asm/ObjectHolderDefinalize.java
  loader/src/main/java/net/neoforged/fml/common/asm/RuntimeDistCleaner.java
  loader/src/main/java/net/neoforged/fml/loading/FMLLoader.java
  loader/src/main/resources/META-INF/services/cpw.mods.modlauncher.serviceapi.ILaunchPluginService
Labels: breaking-change

#51 Deprecate the `mandatory` dependency field and replace it with a `type` field
  core/src/main/java/net/neoforged/fml/ModLoader.java
  core/src/main/java/net/neoforged/fml/ModLoadingWarning.java
  gradle.properties
  loader/src/main/java/net/neoforged/fml/loading/LoadingModList.java
  loader/src/main/java/net/neoforged/fml/loading/ModSorter.java
  loader/src/main/java/net/neoforged/fml/loading/moddiscovery/ModInfo.java
Labels: enhancement, breaking-change

#55 Provide the dependency reason to required dependencies too
  loader/src/main/java/net/neoforged/fml/loading/ModSorter.java
Labels: enhancement

#58 Merge SPI into FML
  build.gradle
  gradle.properties
  loader/build.gradle
  settings.gradle
  spi/build.gradle
  spi/src/main/java/net/neoforged/neoforgespi/Environment.java
  spi/src/main/java/net/neoforged/neoforgespi/coremod/ICoreModFile.java
  spi/src/main/java/net/neoforged/neoforgespi/coremod/ICoreModProvider.java
  spi/src/main/java/net/neoforged/neoforgespi/language/IConfigurable.java
  spi/src/main/java/net/neoforged/neoforgespi/language/ILifecycleEvent.java
  spi/src/main/java/net/neoforged/neoforgespi/language/IModFileInfo.java
  spi/src/main/java/net/neoforged/neoforgespi/language/IModInfo.java
  spi/src/main/java/net/neoforged/neoforgespi/language/IModLanguageProvider.java
  spi/src/main/java/net/neoforged/neoforgespi/language/MavenVersionAdapter.java
  spi/src/main/java/net/neoforged/neoforgespi/language/ModFileScanData.java
  spi/src/main/java/net/neoforged/neoforgespi/locating/ForgeFeature.java
  spi/src/main/java/net/neoforged/neoforgespi/locating/IDependencyLocator.java
  spi/src/main/java/net/neoforged/neoforgespi/locating/IModDirectoryLocatorFactory.java
  spi/src/main/java/net/neoforged/neoforgespi/locating/IModFile.java
  spi/src/main/java/net/neoforged/neoforgespi/locating/IModLocator.java
  spi/src/main/java/net/neoforged/neoforgespi/locating/IModProvider.java
  spi/src/main/java/net/neoforged/neoforgespi/locating/ModFileFactory.java
  spi/src/main/java/net/neoforged/neoforgespi/locating/ModFileLoadingException.java
  spi/src/test/java/net/neoforged/neoforgespi/language/ModInfoTest.java
Labels: enhancement

#60 Only crash if mods found by the MC locator (i.e. dev mods) are using the `mandatory` field
  loader/src/main/java/net/neoforged/fml/loading/moddiscovery/ModInfo.java
Labels: enhancement

#61 Remove annoying logging caused by netty
  loader/src/main/resources/log4j2.xml
Labels: enhancement
