Repository neoforged/FancyModLoader, pull requests merged in 2024-05, with the labels that each got.

#126 Rewrite locators and allow for multiple entrypoints per mod
  loader/build.gradle
  loader/src/main/java/net/neoforged/fml/ModContainer.java
  loader/src/main/java/net/neoforged/fml/ModList.java
  loader/src/main/java/net/neoforged/fml/ModLoader.java
  loader/src/main/java/net/neoforged/fml/common/Mod.java
  loader/src/main/java/net/neoforged/fml/javafmlmod/AutomaticEventSubscriber.java
  loader/src/main/java/net/neoforged/fml/javafmlmod/FMLJavaModLanguageProvider.java
  loader/src/main/java/net/neoforged/fml/javafmlmod/FMLModContainer.java
  loader/src/main/java/net/neoforged/fml/loading/LanguageProviderLoader.java
  loader/src/main/java/net/neoforged/fml/loading/StringSubstitutor.java
  loader/src/main/java/net/neoforged/fml/loading/moddiscovery/ModFile.java
  loader/src/main/java/net/neoforged/fml/loading/moddiscovery/ModInfo.java
  loader/src/main/java/net/neoforged/fml/loading/modscan/ModAnnotation.java
  loader/src/main/java/net/neoforged/fml/loading/modscan/ModClassVisitor.java
  loader/src/main/java/net/neoforged/fml/loading/modscan/Scanner.java
  loader/src/main/java/net/neoforged/fml/lowcodemod/LowCodeModContainer.java
  loader/src/main/java/net/neoforged/fml/lowcodemod/LowCodeModLanguageProvider.java
  loader/src/main/java/net/neoforged/fml/mclanguageprovider/MinecraftModContainer.java
  loader/src/main/java/net/neoforged/fml/mclanguageprovider/MinecraftModLanguageProvider.java
  loader/src/main/java/net/neoforged/neoforgespi/language/IModInfo.java
  loader/src/main/java/net/neoforged/neoforgespi/language/IModLanguageLoader.java
  loader/src/main/java/net/neoforged/neoforgespi/language/ModFileScanData.java
  loader/src/main/java/net/neoforged/neoforgespi/locating/IModFile.java
  loader/src/main/resources/META-INF/services/net.neoforged.neoforgespi.language.IModLanguageLoader
  loader/src/test/java/net/neoforged/fml/test/RuntimeCompiler.java
  loader/src/test/java/net/neoforged/fml/test/TestModFile.java
  loader/src/test/java/net/neoforged/neoforgespi/language/ScanDataTest.java
Labels: enhancement, breaking-change

#128 Move some translations to FML
  crowdin.yml
  loader/src/main/java/net/neoforged/fml/Bindings.java
  loader/src/main/java/net/neoforged/fml/IBindingsProvider.java
  loader/src/main/java/net/neoforged/fml/ModLoadingIssue.java
  loader/src/main/java/net/neoforged/fml/i18n/FMLTranslations.java
  loader/src/main/java/net/neoforged/fml/i18n/I18nManager.java
  loader/src/main/java/net/neoforged/fml/i18n/MavenVersionTranslator.java
  loader/src/main/resources/lang/en_us.json
  loader/src/test/java/net/neoforged/fml/loading/FMLLoaderTest.java
Labels: enhancement

#131 New Crowdin updates
  loader/src/main/resources/lang/da_dk.json
  loader/src/main/resources/lang/de_de.json
  loader/src/main/resources/lang/en_gb.json
  loader/src/main/resources/lang/es_es.json
  loader/src/main/resources/lang/et_ee.json
  loader/src/main/resources/lang/fr_fr.json
  loader/src/main/resources/lang/hu_hu.json
  loader/src/main/resources/lang/it_it.json
  loader/src/main/resources/lang/ja_jp.json
  loader/src/main/resources/lang/ko_kr.json
  loader/src/main/resources/lang/nl_nl.json
  loader/src/main/resources/lang/pl_pl.json
  loader/src/main/resources/lang/ro_ro.json
  loader/src/main/resources/lang/ru_ru.json
  loader/src/main/resources/lang/sk_sk.json
  loader/src/main/resources/lang/tr_tr.json
  loader/src/main/resources/lang/tt_ru.json
  loader/src/main/resources/lang/uk_ua.json
  loader/src/main/resources/lang/zh_cn.json
  loader/src/main/resources/lang/zh_hk.json
Labels: l10n

#134 Allow FML translations to use the vanilla format specifier
  loader/src/main/java/net/neoforged/fml/i18n/FMLTranslations.java
  loader/src/test/java/net/neoforged/fml/test/TranslationPatternsTest.java
Labels: enhancement

#135 Allow IModLanguageLoaders to specify their version
  loader/src/main/java/net/neoforged/fml/javafmlmod/FMLJavaModLanguageProvider.java
  loader/src/main/java/net/neoforged/fml/loading/BuiltInLanguageLoader.java
  loader/src/main/java/net/neoforged/fml/loading/LanguageProviderLoader.java
  loader/src/main/java/net/neoforged/fml/lowcodemod/LowCodeModLanguageProvider.java
  loader/src/main/java/net/neoforged/fml/mclanguageprovider/MinecraftModLanguageProvider.java
  loader/src/main/java/net/neoforged/neoforgespi/language/IModLanguageLoader.java
Labels: enhancement, breaking-change

#137 Safeguard against crashes if the PerformanceInfo fails to update
  earlydisplay/src/main/java/net/neoforged/fml/earlydisplay/PerformanceInfo.java
Labels: bug

#145 Be more specific about @Mod initializer order
  loader/src/main/java/net/neoforged/fml/common/Mod.java
  loader/src/main/java/net/neoforged/fml/javafmlmod/FMLJavaModLanguageProvider.java
  loader/src/test/java/net/neoforged/fml/javafmlmod/FMLJavaModLanguageProviderTest.java
Labels: enhancement

#54 Add a subproject with a JUnit session listener
  build.gradle
  junit/build.gradle
  junit/src/main/java/module-info.java
  junit/src/main/java/net/neoforged/fml/junit/JUnitService.java
  junit/src/main/java/net/neoforged/fml/junit/LaunchWrapper.java
  junit/src/main/resources/META-INF/services/org.junit.platform.launcher.LauncherSessionListener
  loader/build.gradle
  loader/src/main/java/net/neoforged/fml/loading/targets/JUnitDevLaunchTarget.java
  loader/src/main/java/net/neoforged/fml/loading/targets/JUnitUserDevLaunchTarget.java
  loader/src/main/resources/META-INF/services/cpw.mods.modlauncher.api.ILaunchHandlerService
  settings.gradle
Labels: enhancement
