Repository neoforged/FancyModLoader, pull requests merged in 2024-03, with the labels that each got.

#94 Switch to Fabric Mixin
  gradle.properties
  loader/build.gradle
  loader/src/main/java/net/neoforged/fml/loading/LoadingModList.java
  loader/src/main/java/net/neoforged/fml/loading/MixinSyntheticPackageProvider.java
  loader/src/main/java/net/neoforged/fml/loading/mixin/DeferredMixinConfigRegistration.java
  loader/src/main/resources/META-INF/services/cpw.mods.modlauncher.api.ITransformationService
Labels: enhancement

#100 Rename mods.toml to neoforge.mods.toml
  loader/src/main/java/net/neoforged/fml/ModLoader.java
  loader/src/main/java/net/neoforged/fml/loading/moddiscovery/AbstractModProvider.java
  loader/src/main/java/net/neoforged/fml/loading/moddiscovery/ExplodedDirectoryLocator.java
  loader/src/main/java/net/neoforged/fml/loading/moddiscovery/ModFileParser.java
  loader/src/main/java/net/neoforged/fml/loading/targets/CommonDevLaunchHandler.java
Labels: enhancement, breaking-change

#96 Make jarjar use LIBRARY not GAMELIBRARY by default
  loader/src/main/java/net/neoforged/fml/loading/moddiscovery/JarInJarDependencyLocator.java
Labels: breaking-change

#80 Simplify extension point system
  loader/src/main/java/net/neoforged/fml/IExtensionPoint.java
  loader/src/main/java/net/neoforged/fml/ModContainer.java
  loader/src/main/java/net/neoforged/fml/ModLoadingContext.java
Labels: breaking-change

#106 Use CoreMods directly instead of going through SPI abstraction
  gradle.properties
  loader/src/main/java/net/neoforged/fml/ModLoader.java
  loader/src/main/java/net/neoforged/fml/core/ParallelTransition.java
  loader/src/main/java/net/neoforged/fml/loading/FMLEnvironment.java
  loader/src/main/java/net/neoforged/fml/loading/FMLLoader.java
  loader/src/main/java/net/neoforged/fml/loading/FMLServiceProvider.java
  loader/src/main/java/net/neoforged/fml/loading/LoadingModList.java
  loader/src/main/java/net/neoforged/fml/loading/MCPNamingService.java
  loader/src/main/java/net/neoforged/fml/loading/MixinSyntheticPackageProvider.java
  loader/src/main/java/net/neoforged/fml/loading/ModDirTransformerDiscoverer.java
  loader/src/main/java/net/neoforged/fml/loading/ModJarURLHandler.java
  loader/src/main/java/net/neoforged/fml/loading/moddiscovery/CoreModFile.java
  loader/src/main/java/net/neoforged/fml/loading/moddiscovery/InvalidModIdentifier.java
  loader/src/main/java/net/neoforged/fml/loading/moddiscovery/ModFile.java
  loader/src/main/java/net/neoforged/fml/loading/moddiscovery/ModFileInfo.java
  loader/src/main/java/net/neoforged/fml/loading/moddiscovery/ModsFolderLocator.java
  loader/src/main/java/net/neoforged/fml/loading/targets/CommonClientLaunchHandler.java
  loader/src/main/java/net/neoforged/fml/loading/targets/CommonDevLaunchHandler.java
  loader/src/main/java/net/neoforged/fml/loading/targets/CommonLaunchHandler.java
  loader/src/main/java/net/neoforged/fml/loading/targets/CommonServerLaunchHandler.java
  loader/src/main/java/net/neoforged/fml/util/ObfuscationReflectionHelper.java
  spi/src/main/java/net/neoforged/neoforgespi/coremod/ICoreModFile.java
  spi/src/main/java/net/neoforged/neoforgespi/coremod/ICoreModProvider.java
Labels: breaking-change, cleanup

#105 Remove FMLModType.LANGPROVIDER (you can use LIBRARY instead)
  build.gradle
  loader/src/main/java/net/neoforged/fml/loading/moddiscovery/ModValidator.java
  spi/src/main/java/net/neoforged/neoforgespi/language/IModLanguageProvider.java
  spi/src/main/java/net/neoforged/neoforgespi/locating/IModFile.java
Labels: breaking-change, cleanup

#104 Remove OptionalMod
  loader/src/main/java/net/neoforged/fml/OptionalMod.java
Labels: breaking-change, cleanup
