Repository neoforged/FancyModLoader, pull requests merged in 2024-01, with the labels that each got.

#70 Check for explicitly set logger config before overwriting it
  loader/src/main/java/net/neoforged/fml/loading/targets/CommonLaunchHandler.java
Labels: enhancement

#77 Remove legacy ServerMain and empty ICrashCallable
  loader/src/main/java/net/neoforged/fml/ICrashCallable.java
  loader/src/main/java/net/neoforged/fml/server/ServerMain.java
Labels: cleanup

#75 Restore log4j configuration override in prod
  loader/src/main/java/net/neoforged/fml/loading/targets/CommonLaunchHandler.java
Labels: bug
